"""Break captured first requests into system / tools / injected context / prompt
and count chars, UTF-8 bytes and o200k_base tokens.

usage: uvx --with tiktoken python analyze.py [label-glob ...]
Writes analysis.json and prints a markdown table.
"""

import glob
import json
import os
import sys

import tiktoken

ENC = tiktoken.get_encoding("o200k_base")
ROOT = os.path.dirname(os.path.abspath(__file__))
PROMPTS = {"hi"}


def tok(s):
    return len(ENC.encode(s, disallowed_special=()))


def texts_of(content):
    """Yield text strings from a message content (str or list of parts)."""
    if content is None:
        return
    if isinstance(content, str):
        yield content
        return
    for p in content:
        if isinstance(p, str):
            yield p
        elif isinstance(p, dict):
            for k in ("text", "input_text", "output_text"):
                if isinstance(p.get(k), str):
                    yield p[k]
            if p.get("type") not in ("text", "input_text", "output_text") and "text" not in p:
                yield json.dumps(p, ensure_ascii=False)


class Acc:
    def __init__(self):
        self.parts = []

    def add(self, s):
        if s:
            self.parts.append(s)

    def stats(self):
        s = "\n".join(self.parts)
        return {"chars": len(s), "bytes": len(s.encode()), "tokens": tok(s) if s else 0,
                "n": len(self.parts)}


INSTR_MARKERS = ("# AGENTS.md instructions", "Codebase and user instructions are shown below",
                 "Contents of /home/graehl/.claude/CLAUDE.md", "<!-- Generated by ~/agents/scripts/build-boot")
BASE_MARKERS = ("You are Codex,",)


def is_instr(t):
    return any(m in t[:400] for m in INSTR_MARKERS)


CC_SKILLS = "The following skills are available for use with the Skill tool:"


def carve_span(t, start, end, out):
    """Move t[start-marker .. end-marker] into out; end=None means to end of text."""
    i = t.find(start)
    if i < 0:
        return t
    if end is None:
        j = len(t)
    else:
        j = t.find(end, i + len(start))
        j = len(t) if j < 0 else (j + len(end) if end.startswith("</") else j)
    out.add(t[i:j])
    return t[:i] + t[j:]


def carve_cc_skills(t, out):
    i = t.find(CC_SKILLS)
    if i < 0:
        return t
    lines = t[i:].split("\n")
    k = 1
    while k < len(lines):
        if lines[k] == "" and (k + 1 >= len(lines) or not lines[k + 1].startswith("- ")):
            break
        k += 1
    span = "\n".join(lines[:k])
    out.add(span)
    return t[:i] + t[i + len(span):]


def carve(t, instr, skills):
    """Strip instruction-file and skills-catalog spans out of a text part."""
    if is_instr(t):
        instr.add(t)
        return ""
    t = carve_span(t, "<project_context>", "</project_context>", instr)
    t = carve_span(t, "<custom_instruction>", "</custom_instruction>", instr)
    t = carve_span(t, "Instructions from: ", "<available_skills>", instr)
    t = carve_span(t, "<available_skills>", "</available_skills>", skills)
    t = carve_span(t, "<skills_instructions>", "</skills_instructions>", skills)
    t = carve_cc_skills(t, skills)
    return t


def split(api, b):
    sys_, ctx, prompt, instr, skills = Acc(), Acc(), Acc(), Acc(), Acc()
    tools = list(b.get("tools") or [])
    if api == "responses":
        for m in b.get("input") or []:
            if isinstance(m, dict) and m.get("type") == "additional_tools":
                tools.extend(m.get("tools") or [])
    if api == "anthropic":
        s = b.get("system")
        for t in texts_of(s if isinstance(s, list) else ([{"text": s}] if s else [])):
            sys_.add(carve(t, instr, skills))
        msgs = b.get("messages", [])
    elif api == "chat":
        msgs = b.get("messages", [])
    else:  # responses
        if b.get("instructions"):
            sys_.add(carve(b["instructions"], instr, skills))
        msgs = [m for m in b.get("input", []) if isinstance(m, dict)]
        if isinstance(b.get("input"), str):
            msgs = [{"role": "user", "content": b["input"]}]
    have_sys = bool(sys_.parts)
    for m in msgs:
        if m.get("type") == "additional_tools":
            continue
        role = m.get("role") or m.get("type")
        for t in texts_of(m.get("content")):
            # First system/developer message is the harness system prompt; later
            # developer messages are injected context.
            if role == "user" and "<current_datetime>" in t:
                t = carve_span(t, "<current_datetime>", "</current_datetime>", ctx)
            if role == "user" and t.strip() in PROMPTS:
                prompt.add(t.strip())
                continue
            t = carve(t, instr, skills)
            if role in ("system", "developer") and api != "anthropic" and not have_sys:
                have_sys = True
                sys_.add(t)
            elif role == "system" and api != "anthropic":
                sys_.add(t)
            else:
                ctx.add(t)
    tj = json.dumps(tools, ensure_ascii=False, separators=(",", ":")) if tools else ""
    n = sum(len(t.get("tools") or []) if t.get("type") == "namespace" else 1 for t in tools)
    tstat = {"n": n, "chars": len(tj), "bytes": len(tj.encode()),
             "tokens": tok(tj) if tj else 0}
    return sys_.stats(), tstat, instr.stats(), skills.stats(), ctx.stats(), prompt.stats()


def api_of(path):
    p = path.split("?")[0]
    if p.endswith("/messages"):
        return "anthropic"
    if p.endswith("/chat/completions"):
        return "chat"
    if p.endswith("/responses"):
        return "responses"
    return None


def main(pats):
    runs = sorted(glob.glob(os.path.join(ROOT, "runs", "*")))
    if pats:
        runs = [r for r in runs if any(glob.fnmatch.fnmatch(os.path.basename(r), p) for p in pats)]
    rows = []
    for r in runs:
        for f in sorted(glob.glob(os.path.join(r, "*POST*.json"))):
            rec = json.load(open(f))
            api = api_of(rec["path"])
            if not api or not isinstance(rec["body"], dict):
                continue
            s, t, i, k, c, p = split(api, rec["body"])
            total = s["tokens"] + t["tokens"] + i["tokens"] + k["tokens"] + c["tokens"] + p["tokens"]
            rows.append({"label": os.path.basename(r), "file": os.path.basename(f), "api": api,
                         "model": rec["body"].get("model"), "body_bytes": rec["body_bytes"],
                         "system": s, "tools": t, "instr": i, "skills": k, "ctx": c, "prompt": p,
                         "total_tokens": total})
    # the largest generation request per run is the agent turn; smaller ones are side calls
    big = {}
    for x in rows:
        if x["body_bytes"] > big.get(x["label"], 0):
            big[x["label"]] = x["body_bytes"]
    for x in rows:
        x["main"] = x["body_bytes"] == big[x["label"]]
    json.dump(rows, open(os.path.join(ROOT, "analysis.json"), "w"), indent=1)
    print("| run | req | api | model | body B | sys ch/tok | tools n/tok | instr-file ch/tok "
          "| skills ch/tok | other ctx ch/tok | prompt tok | total tok |")
    print("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for x in rows:
        side = "" if x["main"] else " (side)"
        print(f"| {x['label']}{side} | {x['file'][:3]} | {x['api']} | {x['model']} | {x['body_bytes']} | "
              f"{x['system']['chars']}/{x['system']['tokens']} | {x['tools']['n']}/{x['tools']['tokens']} | "
              f"{x['instr']['chars']}/{x['instr']['tokens']} | {x['skills']['chars']}/{x['skills']['tokens']} | "
              f"{x['ctx']['chars']}/{x['ctx']['tokens']} | {x['prompt']['tokens']} | {x['total_tokens']} |")


if __name__ == "__main__":
    main(sys.argv[1:])
